# Generated by Django 2.2.7 on 2019-11-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter Title', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AdultingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter Title', max_length=300)),
                ('summary', models.CharField(default='Enter Summary', max_length=500)),
                ('details', models.TextField(default='Enter Details')),
                ('taskpic', models.TextField(default='No Picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='adultingapp.Category')),
            ],
        ),
    ]
