# Generated by Django 2.2.7 on 2019-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adultingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultingtask',
            name='taskpic',
            field=models.TextField(blank=True, default='No Picture', null=True),
        ),
    ]
